# Generated by Django 3.1.5 on 2021-01-14 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fps_glavni', '0003_auto_20150221_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amount',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amounts', to='fps_glavni.politicalparty', verbose_name='Politička stranka'),
        ),
    ]
